### ISSUE TITLE
"Unregistered type" error you're encountering when using Ceres Solver with PyCOLMAP

### ISSUE THREAD

**Issue by vholod** [cvg/pyceres#51]
Hi,
I get the following error when I try to run the test_BA.ipynb notebook in the examples.

TypeError: Unregistered type : ceres::AutoDiffCostFunction<colmap::ReprojErrorConstantPoseCostFunction<colmap::SimplePinholeCameraModel>, 2, 3, 3>

I installed the colmap and pycolmap from source.
Thus error I get when I install pyceres with `pip install pyceres` (version 2.2) or when I install pyceres from source (somehow the version is 2.0).

Please help me to solve the issue.
Thanks

**Comment by sarlinpe** [comment]
Did you try installing pyceres from source?

**Comment by B1ueber2y** [comment]
Likely due to https://github.com/cvg/pyceres/pull/52. This has been fixed now. We may want to make a new release ASAP and add docs somewhere (on pycolmap 3.10 needs the new ceres release) @sarlinpe

**Comment by sarlinpe** [comment]
@vholod could you try building pyceres at HEAD? we've also pushed a new release v2.3, does this work too when pulled from pypi?

**Comment by vholod** [comment]
Hi,
Thanks for your responses.
I now have many problems to install pyceres from source. I will try to progress with it.

However, when I install pyceres with pip (version 2.3), I still get the problem below.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: Unregistered type : ceres::AutoDiffCostFunction<colmap::ReprojErrorConstantPoseCostFunction<colmap::SimplePinholeCameraModel>, 2, 3, 3>

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[6], line 2
      1 rec = create_reconstruction()
----> 2 problem = define_problem(rec)
      3 solve(problem)

Cell In[5], line 7, in define_problem(rec)
      5     cam = rec.cameras[im.camera_id]
      6     for p in im.points2D:
----> 7         cost = pycolmap.cost_functions.ReprojErrorCost(
      8             cam.model, im.cam_from_world, p.xy
      9         )
     10         prob.add_residual_block(
     11             cost, loss, [rec.points3D[p.point3D_id].xyz, cam.params]
     12         )
     13 for cam in rec.cameras.values():

TypeError: Unable to convert function return value to a Python type! The signature was
	(camera_model_id: pycolmap.CameraModelId, cam_from_world: pycolmap.Rigid3d, point2D: numpy.ndarray[numpy.float64[2, 1]]) -> ceres::CostFunction

**Comment by sarlinpe** [comment]
pyceres and pycolmap need to be either both installed from source or both installed from pypi.

**Comment by vholod** [comment]
Hi ,
I didn't solve it.
However, after some time, the package was updated, so everything worked well for me using Pip install.

________________________________
